---

- name:
  get_url:
    url: "{{ install_script_url }}"
    dest: "/tmp/aws-inspector-agent-install"
    validate_certs: no

- name: run installer
  command: bash /tmp/aws-inspector-agent-install
